### PR TITLE
Update MuteSystem.cs

### PR DESCRIPTION
**Pull request by CactusJoan**
Change the initial warden mute time to baseTime / 2 from baseTime
 This will make rounds more fun :)
Ts can talk after 15-30 secs instead 30-60 secs

### CODE REVIEW

**Comment by ntm5** [comment]
No thanks, warden needs time to give commands

**Comment by CactusJoan** [comment]
> No thanks, warden needs time to give commands

But its too long of a time and after warden gives commands its awkward 
we should shorten time

**Comment by jithatsonei** [comment]
this should honestly be configurable instead of just changing the var again, so that server operators can choose their own time if they wish that works for their community

**Comment by MSWS** [comment]
@CactusJoan this change would introduce half-second increments (e.g. from 5-10 prisoners it would mute for 17.5 seconds). I'd like to keep the mute timings to discrete seconds only (i.e. 17 or 18 seconds). What do you think would be a good compromise? I think rounding up would be the simplest way to resolve this.

**Comment by CactusJoan** [comment]
> @CactusJoan this change would introduce half-second increments (e.g. from 5-10 prisoners it would mute for 17.5 seconds). I'd like to keep the mute timings to discrete seconds only (i.e. 17 or 18 seconds). What do you think would be a good compromise? I think rounding up would be the simplest way to resolve this.

Sounds good :)

**Comment by MSWS** [comment]
> > @CactusJoan this change would introduce half-second increments (e.g. from 5-10 prisoners it would mute for 17.5 seconds). I'd like to keep the mute timings to discrete seconds only (i.e. 17 or 18 seconds). What do you think would be a good compromise? I think rounding up would be the simplest way to resolve this.
> 
> Sounds good :)

Please update this MR with that change, and switch the target to dev, and I will merge.

**Comment by CactusJoan** [comment]
> > > @CactusJoan this change would introduce half-second increments (e.g. from 5-10 prisoners it would mute for 17.5 seconds). I'd like to keep the mute timings to discrete seconds only (i.e. 17 or 18 seconds). What do you think would be a good compromise? I think rounding up would be the simplest way to resolve this.
> > 
> > 
> > Sounds good :)
> 
> Please update this MR with that change, and switch the target to dev, and I will merge.

I think i did it :/

**Pull request merged**
