### PR TITLE
css_fire 

### PR DESCRIPTION
**Pull request by P250**
- Support for css_fire (with @css/generic permission required)
- Integrates with peacemute i.e. if warden has peacemute active and is fired, the peacemute is also revoked

### CODE REVIEW

**Comment by Spock8901** [comment]
will this work when an admin is forced to use the command?

**Comment by P250** [comment]
> will this work when an admin is forced to use the command?

I’ve tested it alone and the warden was indeed fired, and they need the @css/generic permission. I’m not sure what else you mean :)

**Comment by Spock8901** [comment]
> > will this work when an admin is forced to use the command?
> 
> I’ve tested it alone and the warden was indeed fired, and they need the @css/generic permission. I’m not sure what else you mean :)

oh wait thought it said peace sry 6 hours ago i woke up at that time

**Comment by Mooshua** [comment]
This is a pretty big PR @P250. Did you mean to do commit all of this?
No worries if so, just going to take a bit to review.

**Comment by Mooshua** [comment]
In case you aren't aware. Every time you `using static` to prettify a static field access a cute puppy dies a painful death. (No change needed)

**Comment by Mooshua** [comment]
@P250 If you're okay, I'd like to retarget this into a feature branch to do some refactorings around the event system you've got. I agree it's somewhat needed I just want it to be more servicecollection-oriented.

Submitted some minor change requests in the review. Haven't finished reviewing the timer shenanigans or the big changes.
Thanks for your time! This is great work.

**Comment by P250** [comment]
> @P250 If you're okay with it, I'd like to retarget this into a feature branch to do some refactorings around the event system you've got. I agree it's somewhat needed I just want it to be more servicecollection-oriented.
> 
> Submitted some minor change requests in the review. Haven't finished reviewing the timer shenanigans or the big changes. Thanks for your time! This is great work.

Honestly change what you'd like man! I have a question though, if another one of my branches uses the event system or other parts of peace-mute, will your changes affect that?

**Comment by P250** [comment]
> This is a pretty big PR @P250. Did you mean to do commit all of this? No worries if so, just going to take a bit to review.

Yes, I realised I kinda messed up by not committing smaller changes. Sorry about that.

**Comment by MSWS** [comment]
Will be closing this PR due to the (unnecessary) size of it. Please feel free to clean it up and only PR what actually needs to be changed for a `css_fire` command.

**Pull request closed without merging**
