### PR TITLE
Fix/missing weapons

### PR DESCRIPTION
**Pull request by ShookEagle**
-Add dual berettas
-Fix pickups logging twice

### CODE REVIEW

**Comment by ShookEagle** [comment]
cz75 designer name shows as p250. has no apparent fix

**Comment by MSWS** [comment]
@ShookEagle could we log all drops, and remove the allow-list of names that we log? I can't think of a downside to that.

Also, can you clear the recentWeaponEvents hashset every round, just in case there's some weird behavior that would cause it to continuously grow?

**Comment by ShookEagle** [comment]
all drops as in utilities aswell? only reason i have the list is cause more than just weapons have their parents changed

**Comment by MSWS** [comment]
> all drops as in utilities aswell? only reason i have the list is cause more than just weapons have their parents changed

yep, players can't drop utilities on our server at the very least

**Comment by ShookEagle** [comment]
done

**Pull request merged**
